services:
  postgres:
    container_name: ultimate-postgres
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ultimate-net

  redis:
    container_name: ultimate-redis
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - ultimate-net

  auth:
    container_name: ultimate-auth
    build:
      context: .
      dockerfile: auth_service/Dockerfile
      args:
        - STAGE=${STAGE:-dev}
    restart: on-failure
    environment:
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./auth_service/src:/app
    depends_on:
      - redis
      - postgres
    networks:
      - ultimate-net

  api:
    container_name: ultimate-api
    build:
      context: .
      dockerfile: api_service/Dockerfile
      args:
        - STAGE=${STAGE:-dev}
    volumes:
      - ./api_service/src:/app/src
      - media_data:/media
    networks:
      - ultimate-net

  server:
    container_name: ultimate-server
    dns:
      - 8.8.8.8
      - 8.8.8.4
    restart: on-failure
    build:
      context: .
      dockerfile: proxy_service/Dockerfile
      args:
        - STAGE=${STAGE:-dev}
    volumes:
      - media_data:/media
      - ./client:/app
    depends_on:
      - auth
      - api
    ports:
      - "80:80"
    networks:
      - ultimate-net

volumes:
  postgres_data:
  redis_data:
  media_data:

networks:
  ultimate-net:
    driver: bridge
    name: ultimate-net
    ipam:
      config:
        - subnet: 171.17.0.0/16
          gateway: 171.17.0.1
